name: publica en npmjs

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        name: setup node
        with:
          node-version: 24
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build --if-present
      - run: npm test
      - run: npm publish
